# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
